# Generated by Django 6.0.3 on 2026-09-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_applog_id_alter_chat_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(max_length=16)),
                ('payload', models.TextField(default='{}')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consumed', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to='myapp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to='myapp.user')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['receiver', 'consumed', 'timestamp'], name='myapp_calls_receive_d42234_idx')],
            },
        ),
    ]
