# Generated by Django 6.0.3 on 2026-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_message_image_file_id_message_image_url_message_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
