# Generated by Django 6.0.3 on 2026-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_message_edited_at_message_forwarded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('ban', 'Ban User'), ('unban', 'Unban User'), ('delete', 'Delete User'), ('create', 'Create User'), ('toggle_access', 'Toggle Access'), ('toggle_maintenance', 'Toggle Maintenance'), ('broadcast', 'Send Broadcast'), ('announce', 'Create Announcement'), ('delete_announce', 'Delete Announcement'), ('force_logout', 'Force Logout'), ('warn', 'Warn User'), ('ignore_report', 'Ignore Report'), ('call_reject', 'Reject Call')], max_length=50)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='myapp_admin_timesta_053ce6_idx'), models.Index(fields=['action'], name='myapp_admin_action_454352_idx')],
            },
        ),
    ]
