# Generated by Django 6.0.3 on 2026-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='remote_file_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='shared_files/'),
        ),
    ]
