# Generated by Django 6.0.3 on 2026-09-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_sharedfile_file_url_sharedfile_remote_file_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedFile',
        ),
    ]
